services:
  sportivo-back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sportivo_back_prod
    ports:
      - '3000:3000'
    # IMPORTANTE: 
    # 1. No definimos el servicio de base de datos (sportivo_postgres)
    # 2. No usamos 'depends_on'
    # 3. No mapeamos volúmenes locales (.:/app) porque en producción 
    #    queremos usar el código copiado dentro de la imagen por el Dockerfile.
    # 4. No fijamos DATABASE_URL aquí, así tomará el valor que le des en el dashboard de Render.
    restart: always
