services:
  - type: web
    name: sportivo-backend
    env: node
    region: ohio
    plan: free
    # Comandos nativos para construir y arrancar sin Docker
    buildCommand: "npm ci && npx prisma generate && npm run build"
    startCommand: "npx prisma migrate deploy && npx prisma db seed && npm run start:prod"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sportivo-db
          property: connectionString
      - key: PORT
        value: "3000"
      - key: NODE_VERSION           # <-- AQUÍ DEFINIMOS LA VERSIÓN DE NODE
        value: "22.17.0"
      - key: JWT_SECRET
        generateValue: true
      - key: SALT_ROUNDS
        value: "12"
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
      - key: INTERNAL_API_KEY
        sync: false

databases:
  - name: sportivo-db
    databaseName: sportivodb
    user: sportivouser
    plan: free
    region: ohio
